# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('decicription', models.TextField()),
            ],
            options={
                'db_table': 'producttable',
                'verbose_name_plural': 'products',
            },
        ),
    ]
